name: Deploy 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: npm install -g npm@latest
      - run: npm install
      - run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload files to S3
        run: |
            aws s3 sync ./build s3://sierraonetech.com --region us-east-1 --endpoint-url https://s3.us-east-1.amazonaws.com --acl public-read  --delete --cache-control max-age=604800
            
      - name: Create Cloudfront Invalidation
        run: |
          ID=$(aws cloudfront create-invalidation --distribution-id E22DNOKC6JICU9 --paths '/*' | egrep Id | awk -F'"' '{ print $4}')
          aws cloudfront wait invalidation-completed --id $ID --distribution-id E22DNOKC6JICU9

      - name: Notify Slack
        uses: act10ns/slack@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#deployment-logs'
        if: always()
